In [31]:
import numpy as np
from PIL import Image

In [2]:
# Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


In [3]:
#Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods 
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:")
print(array1)
print("Flatten the array:")
print(array1.flatten())
print("Flatten the array using ravel:")
print(array1.ravel())


Original array:
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Flatten the array:
[1 2 3 2 4 5 1 2 3]
Flatten the array using ravel:
[1 2 3 2 4 5 1 2 3]


In [5]:
#Compare the following numpy arrays: 
#arr1 = np.array([[1, 2], [3, 4]]) 
#arr2 = np.array([[1, 2], [3, 4]]) 
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])
print("arr1 == arr2")
print(arr1 == arr2)


arr1 == arr2
[[ True  True]
 [ True  True]]


In [6]:
#Find the most frequent value and their indice(s) in the following arrays: 
#i.  x = np.array([1,2,3,4,5,1,2,1,1,1]) 
#ii.  y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print("Most frequent value in x is: ", np.bincount(x).argmax())
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print("Most frequent value in y is: ", np.bincount(y).argmax())


Most frequent value in x is:  1
Most frequent value in y is:  1


In [7]:
#For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
#i.  Sum of all elements 
#ii.  Sum of all elements row-wise  
#iii.  Sum of all elements column-wise
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all elements: ", np.sum(gfg))
print("Sum of all elements row-wise: ", np.sum(gfg, axis=1))
print("Sum of all elements column-wise: ", np.sum(gfg, axis=0))

Sum of all elements:  45
Sum of all elements row-wise:  [[14]
 [16]
 [15]]
Sum of all elements column-wise:  [[20  9 16]]


In [8]:
#For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
# i.  Sum of diagonal elements 
# ii.  Eigen values of matrix 
# iii.  Eigen vectors of matrix 
# iv.  Inverse of matrix 
# v.  Determinant of matrix
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("Matrix is: \n",n_array)
print("Sum of diagonal elements is: ",np.trace(n_array))
print("Eigen values of matrix is: ",np.linalg.eigvals(n_array))
print("Eigen vectors of matrix is: ",np.linalg.eig(n_array))
print("Inverse of matrix is: \n",np.linalg.inv(n_array))
print("Determinant of matrix is: ",np.linalg.det(n_array))

Matrix is: 
 [[55 25 15]
 [30 44  2]
 [11 45 77]]
Sum of diagonal elements is:  176
Eigen values of matrix is:  [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix is:  (array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Inverse of matrix is: 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix is:  137180.0000000001


In [10]:
# Multiply the following matrices and also find covariance between matrices using NumPy: 
# i.  p = [[1, 2], [2, 3]] 
#     q = [[4, 5], [6, 7]] 
# ii. p = [[1, 2], [2, 3], [4, 5]] 
#     q = [[4, 5, 1], [6, 7, 2]] 

p1 = [[1, 2], [2, 3]]
q1 = [[4, 5], [6, 7]]
print("Multiplication of matrices p and q is: ",np.matmul(p1,q1))
print("Covariance of matrices p and q is: ",np.cov(p1,q1))

p2 = [[1, 2], [2, 3], [4, 5]]
q2 = [[4, 5, 1], [6, 7, 2]]
print("Multiplication of matrices p and q is: ",np.matmul(p2,q2))
# print("Covariance of matrices p and q is: ",np.cov(p2,q2))

Multiplication of matrices p and q is:  [[16 19]
 [26 31]]
Covariance of matrices p and q is:  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Multiplication of matrices p and q is:  [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [13]:
# For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
# find inner, outer and cartesian product?
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product: ", np.inner(x, y))
print("Outer product: ", np.outer(x, y))
print("Cartesian product: ")
x_mesh, y_mesh = np.meshgrid(x, y)
cartesian_product = np.stack((x_mesh.ravel(), y_mesh.ravel()), axis=-1)
print(cartesian_product)


Inner product:  [[17 52]
 [13 62]]
Outer product:  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product: 
[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


In [17]:
# For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
# i.  Find element-wise absolute value 
# ii.  Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
# row. 
# iii.  Mean, Median and Standard Deviation of flattened array, of each column, and 
# each row
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("Absolute array:\n",np.absolute(array))
print("25th percentile of array:\n",np.percentile(array,25))
print("50th percentile of array:\n",np.percentile(array,50))
print("75th percentile of array:\n",np.percentile(array,75))
print("Mean of array:\n",np.mean(array.flatten()))
print("Median of array:\n",np.median(array.flatten()))
print("Standard deviation of array:\n",np.std(array.flatten()))

Absolute array:
 [[1 2 3]
 [4 5 6]]
25th percentile of array:
 -3.5
50th percentile of array:
 -0.5
75th percentile of array:
 2.5
Mean of array:
 -0.5
Median of array:
 -0.5
Standard deviation of array:
 3.8622100754188224


In [18]:
# For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
# and truncated value, rounded values
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor value of a: ", np.floor(a))
print("Ceiling value of a: ", np.ceil(a))
print("Truncated value of a: ", np.trunc(a))
print("Rounded value of a: ", np.round(a))

Floor value of a:  [-2. -2. -1.  0.  1.  1.  3.]
Ceiling value of a:  [-1. -1. -0.  1.  2.  2.  3.]
Truncated value of a:  [-1. -1. -0.  0.  1.  1.  3.]
Rounded value of a:  [-2. -2. -0.  0.  2.  2.  3.]


In [25]:
# For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
# i.  Sorted array 
# ii.  Indices of sorted array 
# iii.  4 smallest elements 
# iv.  5 largest elements
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:", np.sort(array))
print("Indices of sorted array:", np.argsort(array))
print("4 smallest elements:", np.sort(array)[:4])
a = np.sort(array)[-5:]
print("5 largest elements:", a[::-1])

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


In [27]:
# For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
# i.  Integer elements only 
# ii.  Float elements only
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elem = array[array.astype(int) == array]
float_elem = array[array.astype(int) != array]
print("Integer elements only: ", int_elem)
print("Float elements only: ", float_elem)

Integer elements only:  [1. 2. 3. 2.]
Float elements only:  [1.2 2.2]


In [34]:
# Write a function named img_to_array(path) that reads an image from a specified path and 
# save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
# images)
def img_to_path(path):
    image  = Image.open(path)
    img_array = np.array(image)
    height, width, channel = img_array.shape[:2]
    if len(img_array.shape) == 2:
         # Grayscale image case
        output_filename = "grayscale_array.txt"
        np.savetxt(output_filename, img_array, fmt='%d')
        print(f"Grayscale image array saved as {output_filename}")
    elif len(img_array.shape) == 3 and img_array.shape[2] == 3:
        # RGB image case
        output_filename = "rgb_array.txt"
        np.savetxt(output_filename, img_array.reshape(-1, 3), fmt='%d')
        print(f"RGB image array saved as {output_filename}")
    else:
        print("Unsupported image format.")